//! The [`SpotifyApi`] trait: the mockable Web API surface.
//!
//! Everything in the workspace that needs Spotify data depends on this trait,
//! never on a concrete client. The real implementation
//! ([`SpotifyClient`](crate::SpotifyClient)) is backed by `rspotify`; the
//! [`MockSpotifyApi`] generated by `mockall` lets the UI be developed offline.
//!
//! ## Pagination
//!
//! Bounded endpoints return one [`models::Page`]. Unbounded endpoints
//! (playlists, playlist items, saved tracks/albums, an artist's albums)
//! additionally expose a `*_stream` form returning an [`ItemStream`] that
//! yields every item across every page, following Spotify's `next` links and
//! routing each page request through the retry/rate-limit policy.

use std::pin::Pin;

use async_trait::async_trait;
use futures::stream::Stream;

use spottyfi_models::{
    Album, Artist, Category, Page, Playlist, PlaylistTrack, SearchResults, SimplifiedAlbum,
    SimplifiedPlaylist, Track, User,
};

#[cfg(test)]
use crate::error::ApiError;
use crate::error::ApiResult;

/// A boxed async stream of paginated items.
///
/// Each item is an individual `T` (not a page); a transport error on any page
/// is yielded inline and ends the stream.
pub type ItemStream<T> = Pin<Box<dyn Stream<Item = ApiResult<T>> + Send>>;

/// The kind of object a search should return.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SearchType {
    /// Search tracks.
    Track,
    /// Search artists.
    Artist,
    /// Search albums.
    Album,
    /// Search playlists.
    Playlist,
}

/// The mockable Spotify Web API surface used across the workspace.
///
/// All methods are `async` and fallible with [`ApiError`]. Calls are
/// `#[tracing::instrument]`-ed in the real implementation.
#[mockall::automock]
#[async_trait]
pub trait SpotifyApi: Send + Sync {
    /// The signed-in user's profile (`GET /me`).
    async fn current_user(&self) -> ApiResult<User>;

    /// One page of the signed-in user's playlists (`GET /me/playlists`).
    async fn user_playlists(&self, offset: u32, limit: u32) -> ApiResult<Page<SimplifiedPlaylist>>;

    /// Every playlist of the signed-in user, as a stream.
    fn user_playlists_stream(&self) -> ItemStream<SimplifiedPlaylist>;

    /// A single playlist with its first page of tracks
    /// (`GET /playlists/{id}`).
    async fn playlist(&self, playlist_id: &str) -> ApiResult<Playlist>;

    /// One page of a playlist's tracks (`GET /playlists/{id}/items`).
    async fn playlist_tracks(
        &self,
        playlist_id: &str,
        offset: u32,
        limit: u32,
    ) -> ApiResult<Page<PlaylistTrack>>;

    /// Every track in a playlist, as a stream.
    fn playlist_tracks_stream(&self, playlist_id: &str) -> ItemStream<PlaylistTrack>;

    /// One page of the user's saved ("Liked Songs") tracks (`GET /me/tracks`).
    async fn saved_tracks(&self, offset: u32, limit: u32) -> ApiResult<Page<Track>>;

    /// Every saved track, as a stream.
    fn saved_tracks_stream(&self) -> ItemStream<Track>;

    /// One page of the user's saved albums (`GET /me/albums`).
    async fn saved_albums(&self, offset: u32, limit: u32) -> ApiResult<Page<Album>>;

    /// Every saved album, as a stream.
    fn saved_albums_stream(&self) -> ItemStream<Album>;

    /// A single album with its first page of tracks (`GET /albums/{id}`).
    async fn album(&self, album_id: &str) -> ApiResult<Album>;

    /// A single artist (`GET /artists/{id}`).
    async fn artist(&self, artist_id: &str) -> ApiResult<Artist>;

    /// One page of an artist's albums (`GET /artists/{id}/albums`).
    async fn artist_albums(
        &self,
        artist_id: &str,
        offset: u32,
        limit: u32,
    ) -> ApiResult<Page<SimplifiedAlbum>>;

    /// Every album by an artist, as a stream.
    fn artist_albums_stream(&self, artist_id: &str) -> ItemStream<SimplifiedAlbum>;

    /// An artist's top tracks in the user's market
    /// (`GET /artists/{id}/top-tracks`).
    ///
    /// # Errors
    ///
    /// May fail with [`ApiError::EndpointUnavailable`] — Spotify deprecated
    /// this endpoint for apps registered after 2024-11-27.
    async fn artist_top_tracks(&self, artist_id: &str) -> ApiResult<Vec<Track>>;

    /// A multi-type catalogue search (`GET /search`).
    async fn search(
        &self,
        query: &str,
        types: &[SearchType],
        limit: u32,
    ) -> ApiResult<SearchResults>;

    /// Spotify's featured playlists (`GET /browse/featured-playlists`).
    ///
    /// # Errors
    ///
    /// May fail with [`ApiError::EndpointUnavailable`] — deprecated for apps
    /// registered after 2024-11-27.
    async fn featured_playlists(&self, limit: u32) -> ApiResult<Vec<SimplifiedPlaylist>>;

    /// Spotify's browse categories (`GET /browse/categories`).
    ///
    /// # Errors
    ///
    /// May fail with [`ApiError::EndpointUnavailable`] — deprecated for apps
    /// registered after 2024-11-27.
    async fn browse_categories(&self, limit: u32) -> ApiResult<Vec<Category>>;

    /// Track recommendations seeded by artists, genres and/or tracks
    /// (`GET /recommendations`).
    ///
    /// # Errors
    ///
    /// Very likely to fail with [`ApiError::EndpointUnavailable`] — Spotify
    /// deprecated this endpoint for apps registered after 2024-11-27. Phase 7
    /// (Browse) is expected to source recommendations from Last.fm instead;
    /// see `docs/questions.md`.
    async fn recommendations(
        &self,
        seed_artists: &[String],
        seed_tracks: &[String],
        seed_genres: &[String],
        limit: u32,
    ) -> ApiResult<Vec<Track>>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use spottyfi_models::UserId;

    #[tokio::test]
    async fn mock_can_stand_in_for_the_real_client() {
        let mut mock = MockSpotifyApi::new();
        mock.expect_current_user().returning(|| {
            Ok(User {
                id: UserId::new("offline-dev"),
                display_name: Some("Offline Dev".to_owned()),
                images: Vec::new(),
            })
        });

        let user = mock.current_user().await.expect("mock returns Ok");
        assert_eq!(user.id.0, "offline-dev");
        assert_eq!(user.display_name.as_deref(), Some("Offline Dev"));
    }

    #[tokio::test]
    async fn mock_can_simulate_a_deprecated_endpoint() {
        let mut mock = MockSpotifyApi::new();
        mock.expect_recommendations().returning(|_, _, _, _| {
            Err(ApiError::EndpointUnavailable {
                endpoint: "recommendations",
            })
        });

        let err = mock
            .recommendations(&[], &[], &[], 20)
            .await
            .expect_err("deprecated endpoint should error");
        assert!(matches!(
            err,
            ApiError::EndpointUnavailable {
                endpoint: "recommendations"
            }
        ));
    }
}
